// Create types
export const GENERAL_CREATE_ERROR = 'GENERAL_CREATE_ERROR';
export const GENERAL_CREATE_LOADING = 'GENERAL_CREATE_LOADING';
export const GENERAL_CREATE_SUCCESS = 'GENERAL_CREATE_SUCCESS';
export const GENERAL_CREATE_VIOLATIONS = 'GENERAL_CREATE_VIOLATIONS';
export const GENERAL_CREATE_RESET = 'GENERAL_CREATE_RESET';

// Update types
export const GENERAL_UPDATE_RESET = 'GENERAL_UPDATE_RESET';
export const GENERAL_UPDATE_UPDATE_ERROR = 'GENERAL_UPDATE_UPDATE_ERROR';
export const GENERAL_UPDATE_UPDATE_LOADING = 'GENERAL_UPDATE_UPDATE_LOADING';
export const GENERAL_UPDATE_UPDATE_SUCCESS = 'GENERAL_UPDATE_UPDATE_SUCCESS';
export const GENERAL_UPDATE_RETRIEVE_ERROR = 'GENERAL_UPDATE_RETRIEVE_ERROR';
export const GENERAL_UPDATE_RETRIEVE_LOADING = 'GENERAL_UPDATE_RETRIEVE_LOADING';
export const GENERAL_UPDATE_RETRIEVE_SUCCESS = 'GENERAL_UPDATE_RETRIEVE_SUCCESS';
export const GENERAL_UPDATE_UPDATE_VIOLATIONS = 'GENERAL_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const GENERAL_DELETE_ERROR = 'GENERAL_DELETE_ERROR';
export const GENERAL_DELETE_LOADING = 'GENERAL_DELETE_LOADING';
export const GENERAL_DELETE_SUCCESS = 'GENERAL_DELETE_SUCCESS';
export const GENERAL_DELETE_RESET = 'GENERAL_DELETE_RESET';

// List types
export const GENERAL_LIST_ERROR = 'GENERAL_LIST_ERROR';
export const GENERAL_LIST_LOADING = 'GENERAL_LIST_LOADING';
export const GENERAL_LIST_RESET = 'GENERAL_LIST_RESET';
export const GENERAL_LIST_VIEW = 'GENERAL_LIST_VIEW';
export const GENERAL_LIST_SUCCESS = 'GENERAL_LIST_SUCCESS';
