// Create types
export const CONFIG_CREATE_ERROR = 'CONFIG_CREATE_ERROR';
export const CONFIG_CREATE_LOADING = 'CONFIG_CREATE_LOADING';
export const CONFIG_CREATE_SUCCESS = 'CONFIG_CREATE_SUCCESS';
export const CONFIG_CREATE_VIOLATIONS = 'CONFIG_CREATE_VIOLATIONS';
export const CONFIG_CREATE_RESET = 'CONFIG_CREATE_RESET';


// Update types
export const CONFIG_UPDATE_RESET = 'CONFIG_UPDATE_RESET';
export const CONFIG_UPDATE_UPDATE_ERROR = 'CONFIG_UPDATE_UPDATE_ERROR';
export const CONFIG_UPDATE_UPDATE_LOADING = 'CONFIG_UPDATE_UPDATE_LOADING';
export const CONFIG_UPDATE_UPDATE_SUCCESS = 'CONFIG_UPDATE_UPDATE_SUCCESS';
export const CONFIG_UPDATE_RETRIEVE_ERROR = 'CONFIG_UPDATE_RETRIEVE_ERROR';
export const CONFIG_UPDATE_RETRIEVE_LOADING = 'CONFIG_UPDATE_RETRIEVE_LOADING';
export const CONFIG_UPDATE_RETRIEVE_SUCCESS = 'CONFIG_UPDATE_RETRIEVE_SUCCESS';
export const CONFIG_UPDATE_UPDATE_VIOLATIONS = 'CONFIG_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const CONFIG_DELETE_ERROR = 'CONFIG_DELETE_ERROR';
export const CONFIG_DELETE_LOADING = 'CONFIG_DELETE_LOADING';
export const CONFIG_DELETE_SUCCESS = 'CONFIG_DELETE_SUCCESS';
export const CONFIG_DELETE_RESET = 'CONFIG_DELETE_RESET';

// List types
export const CONFIG_LIST_ERROR = 'CONFIG_LIST_ERROR';
export const CONFIG_LIST_LOADING = 'CONFIG_LIST_LOADING';
export const CONFIG_LIST_RESET = 'CONFIG_LIST_RESET';
export const CONFIG_LIST_VIEW = 'CONFIG_LIST_VIEW';
export const CONFIG_LIST_SUCCESS = 'CONFIG_LIST_SUCCESS';
