// Create types
export const PROVINCE_CREATE_ERROR = 'PROVINCE_CREATE_ERROR';
export const PROVINCE_CREATE_LOADING = 'PROVINCE_CREATE_LOADING';
export const PROVINCE_CREATE_SUCCESS = 'PROVINCE_CREATE_SUCCESS';
export const PROVINCE_CREATE_VIOLATIONS = 'PROVINCE_CREATE_VIOLATIONS';
export const PROVINCE_CREATE_RESET = 'PROVINCE_CREATE_RESET';
// Update types
export const PROVINCE_UPDATE_RESET = 'PROVINCE_UPDATE_RESET';
export const PROVINCE_UPDATE_UPDATE_ERROR = 'PROVINCE_UPDATE_UPDATE_ERROR';
export const PROVINCE_UPDATE_UPDATE_LOADING = 'PROVINCE_UPDATE_UPDATE_LOADING';
export const PROVINCE_UPDATE_UPDATE_SUCCESS = 'PROVINCE_UPDATE_UPDATE_SUCCESS';
export const PROVINCE_UPDATE_RETRIEVE_ERROR = 'PROVINCE_UPDATE_RETRIEVE_ERROR';
export const PROVINCE_UPDATE_RETRIEVE_LOADING = 'PROVINCE_UPDATE_RETRIEVE_LOADING';
export const PROVINCE_UPDATE_RETRIEVE_SUCCESS = 'PROVINCE_UPDATE_RETRIEVE_SUCCESS';
export const PROVINCE_UPDATE_UPDATE_VIOLATIONS = 'PROVINCE_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const PROVINCE_DELETE_ERROR = 'PROVINCE_DELETE_ERROR';
export const PROVINCE_DELETE_LOADING = 'PROVINCE_DELETE_LOADING';
export const PROVINCE_DELETE_SUCCESS = 'PROVINCE_DELETE_SUCCESS';
export const PROVINCE_DELETE_RESET = 'PROVINCE_DELETE_RESET';

// List types
export const PROVINCE_LIST_ERROR = 'PROVINCE_LIST_ERROR';
export const PROVINCE_LIST_LOADING = 'PROVINCE_LIST_LOADING';
export const PROVINCE_LIST_RESET = 'PROVINCE_LIST_RESET';
export const PROVINCE_LIST_VIEW = 'PROVINCE_LIST_VIEW';
export const PROVINCE_LIST_SUCCESS = 'PROVINCE_LIST_SUCCESS';
