api_platform:
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    collection:
            pagination:
                items_per_page: 10 # Default value
                client_enabled: true
                enabled_parameter_name: pagination # optional
