// Create types
export const DESTINATION_CREATE_ERROR = 'DESTINATION_CREATE_ERROR';
export const DESTINATION_CREATE_LOADING = 'DESTINATION_CREATE_LOADING';
export const DESTINATION_CREATE_SUCCESS = 'DESTINATION_CREATE_SUCCESS';
export const DESTINATION_CREATE_VIOLATIONS = 'DESTINATION_CREATE_VIOLATIONS';
export const DESTINATION_CREATE_RESET = 'DESTINATION_CREATE_RESET';

// Show types
export const DESTINATION_SHOW_ERROR = 'DESTINATION_SHOW_ERROR';
export const DESTINATION_SHOW_LOADING = 'DESTINATION_SHOW_LOADING';
export const DESTINATION_SHOW_RETRIEVED_SUCCESS = 'DESTINATION_SHOW_RETRIEVED_SUCCESS';
export const DESTINATION_SHOW_RESET = 'DESTINATION_SHOW_RESET';

// Update types
export const DESTINATION_UPDATE_RESET = 'DESTINATION_UPDATE_RESET';
export const DESTINATION_UPDATE_UPDATE_ERROR = 'DESTINATION_UPDATE_UPDATE_ERROR';
export const DESTINATION_UPDATE_UPDATE_LOADING = 'DESTINATION_UPDATE_UPDATE_LOADING';
export const DESTINATION_UPDATE_UPDATE_SUCCESS = 'DESTINATION_UPDATE_UPDATE_SUCCESS';
export const DESTINATION_UPDATE_RETRIEVE_ERROR = 'DESTINATION_UPDATE_RETRIEVE_ERROR';
export const DESTINATION_UPDATE_RETRIEVE_LOADING = 'DESTINATION_UPDATE_RETRIEVE_LOADING';
export const DESTINATION_UPDATE_RETRIEVE_SUCCESS = 'DESTINATION_UPDATE_RETRIEVE_SUCCESS';
export const DESTINATION_UPDATE_UPDATE_VIOLATIONS = 'DESTINATION_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const DESTINATION_DELETE_ERROR = 'DESTINATION_DELETE_ERROR';
export const DESTINATION_DELETE_LOADING = 'DESTINATION_DELETE_LOADING';
export const DESTINATION_DELETE_SUCCESS = 'DESTINATION_DELETE_SUCCESS';
export const DESTINATION_DELETE_RESET = 'DESTINATION_DELETE_RESET';

// List types
export const DESTINATION_LIST_ERROR = 'DESTINATION_LIST_ERROR';
export const DESTINATION_LIST_LOADING = 'DESTINATION_LIST_LOADING';
export const DESTINATION_LIST_RESET = 'DESTINATION_LIST_RESET';
export const DESTINATION_LIST_VIEW = 'DESTINATION_LIST_VIEW';
export const DESTINATION_LIST_SUCCESS = 'DESTINATION_LIST_SUCCESS';
