// Create types
export const NOTIFICATION_CREATE_ERROR = 'NOTIFICATION_CREATE_ERROR';
export const NOTIFICATION_CREATE_LOADING = 'NOTIFICATION_CREATE_LOADING';
export const NOTIFICATION_CREATE_SUCCESS = 'NOTIFICATION_CREATE_SUCCESS';
export const NOTIFICATION_CREATE_VIOLATIONS = 'NOTIFICATION_CREATE_VIOLATIONS';
export const NOTIFICATION_CREATE_RESET = 'NOTIFICATION_CREATE_RESET';


// Update types
export const NOTIFICATION_UPDATE_RESET = 'NOTIFICATION_UPDATE_RESET';
export const NOTIFICATION_UPDATE_UPDATE_ERROR = 'NOTIFICATION_UPDATE_UPDATE_ERROR';
export const NOTIFICATION_UPDATE_UPDATE_LOADING = 'NOTIFICATION_UPDATE_UPDATE_LOADING';
export const NOTIFICATION_UPDATE_UPDATE_SUCCESS = 'NOTIFICATION_UPDATE_UPDATE_SUCCESS';
export const NOTIFICATION_UPDATE_RETRIEVE_ERROR = 'NOTIFICATION_UPDATE_RETRIEVE_ERROR';
export const NOTIFICATION_UPDATE_RETRIEVE_LOADING = 'NOTIFICATION_UPDATE_RETRIEVE_LOADING';
export const NOTIFICATION_UPDATE_RETRIEVE_SUCCESS = 'NOTIFICATION_UPDATE_RETRIEVE_SUCCESS';
export const NOTIFICATION_UPDATE_UPDATE_VIOLATIONS = 'NOTIFICATION_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const NOTIFICATION_DELETE_ERROR = 'NOTIFICATION_DELETE_ERROR';
export const NOTIFICATION_DELETE_LOADING = 'NOTIFICATION_DELETE_LOADING';
export const NOTIFICATION_DELETE_SUCCESS = 'NOTIFICATION_DELETE_SUCCESS';
export const NOTIFICATION_DELETE_RESET = 'NOTIFICATION_DELETE_RESET';

// List types
export const NOTIFICATION_LIST_ERROR = 'NOTIFICATION_LIST_ERROR';
export const NOTIFICATION_LIST_LOADING = 'NOTIFICATION_LIST_LOADING';
export const NOTIFICATION_LIST_RESET = 'NOTIFICATION_LIST_RESET';
export const NOTIFICATION_LIST_VIEW = 'NOTIFICATION_LIST_VIEW';
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS';
