// Create types
export const LSBOOKING_CREATE_ERROR = 'LSBOOKING_CREATE_ERROR';
export const LSBOOKING_CREATE_LOADING = 'LSBOOKING_CREATE_LOADING';
export const LSBOOKING_CREATE_SUCCESS = 'LSBOOKING_CREATE_SUCCESS';
export const LSBOOKING_CREATE_VIOLATIONS = 'LSBOOKING_CREATE_VIOLATIONS';
export const LSBOOKING_CREATE_RESET = 'LSBOOKING_CREATE_RESET';

// Show types
export const LSBOOKING_SHOW_ERROR = 'LSBOOKING_SHOW_ERROR';
export const LSBOOKING_SHOW_LOADING = 'LSBOOKING_SHOW_LOADING';
export const LSBOOKING_SHOW_RETRIEVED_SUCCESS = 'LSBOOKING_SHOW_RETRIEVED_SUCCESS';
export const LSBOOKING_SHOW_RESET = 'LSBOOKING_SHOW_RESET';

// Update types
export const LSBOOKING_UPDATE_RESET = 'LSBOOKING_UPDATE_RESET';
export const LSBOOKING_UPDATE_UPDATE_ERROR = 'LSBOOKING_UPDATE_UPDATE_ERROR';
export const LSBOOKING_UPDATE_UPDATE_LOADING = 'LSBOOKING_UPDATE_UPDATE_LOADING';
export const LSBOOKING_UPDATE_UPDATE_SUCCESS = 'LSBOOKING_UPDATE_UPDATE_SUCCESS';
export const LSBOOKING_UPDATE_RETRIEVE_ERROR = 'LSBOOKING_UPDATE_RETRIEVE_ERROR';
export const LSBOOKING_UPDATE_RETRIEVE_LOADING = 'LSBOOKING_UPDATE_RETRIEVE_LOADING';
export const LSBOOKING_UPDATE_RETRIEVE_SUCCESS = 'LSBOOKING_UPDATE_RETRIEVE_SUCCESS';
export const LSBOOKING_UPDATE_UPDATE_VIOLATIONS = 'LSBOOKING_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const LSBOOKING_DELETE_ERROR = 'LSBOOKING_DELETE_ERROR';
export const LSBOOKING_DELETE_LOADING = 'LSBOOKING_DELETE_LOADING';
export const LSBOOKING_DELETE_SUCCESS = 'LSBOOKING_DELETE_SUCCESS';
export const LSBOOKING_DELETE_RESET = 'LSBOOKING_DELETE_RESET';

// List types
export const LSBOOKING_LIST_ERROR = 'LSBOOKING_LIST_ERROR';
export const LSBOOKING_LIST_LOADING = 'LSBOOKING_LIST_LOADING';
export const LSBOOKING_LIST_RESET = 'LSBOOKING_LIST_RESET';
export const LSBOOKING_LIST_VIEW = 'LSBOOKING_LIST_VIEW';
export const LSBOOKING_LIST_SUCCESS = 'LSBOOKING_LIST_SUCCESS';
