// Create types
export const AGENT_CREATE_ERROR = 'AGENT_CREATE_ERROR';
export const AGENT_CREATE_LOADING = 'AGENT_CREATE_LOADING';
export const AGENT_CREATE_SUCCESS = 'AGENT_CREATE_SUCCESS';
export const AGENT_CREATE_VIOLATIONS = 'AGENT_CREATE_VIOLATIONS';
export const AGENT_CREATE_RESET = 'AGENT_CREATE_RESET';


// Update types
export const AGENT_UPDATE_RESET = 'AGENT_UPDATE_RESET';
export const AGENT_UPDATE_UPDATE_ERROR = 'AGENT_UPDATE_UPDATE_ERROR';
export const AGENT_UPDATE_UPDATE_LOADING = 'AGENT_UPDATE_UPDATE_LOADING';
export const AGENT_UPDATE_UPDATE_SUCCESS = 'AGENT_UPDATE_UPDATE_SUCCESS';
export const AGENT_UPDATE_RETRIEVE_ERROR = 'AGENT_UPDATE_RETRIEVE_ERROR';
export const AGENT_UPDATE_RETRIEVE_LOADING = 'AGENT_UPDATE_RETRIEVE_LOADING';
export const AGENT_UPDATE_RETRIEVE_SUCCESS = 'AGENT_UPDATE_RETRIEVE_SUCCESS';
export const AGENT_UPDATE_UPDATE_VIOLATIONS = 'AGENT_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const AGENT_DELETE_ERROR = 'AGENT_DELETE_ERROR';
export const AGENT_DELETE_LOADING = 'AGENT_DELETE_LOADING';
export const AGENT_DELETE_SUCCESS = 'AGENT_DELETE_SUCCESS';
export const AGENT_DELETE_RESET = 'AGENT_DELETE_RESET';

// List types
export const AGENT_LIST_ERROR = 'AGENT_LIST_ERROR';
export const AGENT_LIST_LOADING = 'AGENT_LIST_LOADING';
export const AGENT_LIST_RESET = 'AGENT_LIST_RESET';
export const AGENT_LIST_VIEW = 'AGENT_LIST_VIEW';
export const AGENT_LIST_SUCCESS = 'AGENT_LIST_SUCCESS';
