// Create types
export const TRANSFERTOUR_CREATE_ERROR = 'TRANSFERTOUR_CREATE_ERROR';
export const TRANSFERTOUR_CREATE_LOADING = 'TRANSFERTOUR_CREATE_LOADING';
export const TRANSFERTOUR_CREATE_SUCCESS = 'TRANSFERTOUR_CREATE_SUCCESS';
export const TRANSFERTOUR_CREATE_VIOLATIONS = 'TRANSFERTOUR_CREATE_VIOLATIONS';
export const TRANSFERTOUR_CREATE_RESET = 'TRANSFERTOUR_CREATE_RESET';

// Show types
export const TRANSFERTOUR_SHOW_ERROR = 'TRANSFERTOUR_SHOW_ERROR';
export const TRANSFERTOUR_SHOW_LOADING = 'TRANSFERTOUR_SHOW_LOADING';
export const TRANSFERTOUR_SHOW_RETRIEVED_SUCCESS = 'TRANSFERTOUR_SHOW_RETRIEVED_SUCCESS';
export const TRANSFERTOUR_SHOW_RESET = 'TRANSFERTOUR_SHOW_RESET';

// Update types
export const TRANSFERTOUR_UPDATE_RESET = 'TRANSFERTOUR_UPDATE_RESET';
export const TRANSFERTOUR_UPDATE_UPDATE_ERROR = 'TRANSFERTOUR_UPDATE_UPDATE_ERROR';
export const TRANSFERTOUR_UPDATE_UPDATE_LOADING = 'TRANSFERTOUR_UPDATE_UPDATE_LOADING';
export const TRANSFERTOUR_UPDATE_UPDATE_SUCCESS = 'TRANSFERTOUR_UPDATE_UPDATE_SUCCESS';
export const TRANSFERTOUR_UPDATE_RETRIEVE_ERROR = 'TRANSFERTOUR_UPDATE_RETRIEVE_ERROR';
export const TRANSFERTOUR_UPDATE_RETRIEVE_LOADING = 'TRANSFERTOUR_UPDATE_RETRIEVE_LOADING';
export const TRANSFERTOUR_UPDATE_RETRIEVE_SUCCESS = 'TRANSFERTOUR_UPDATE_RETRIEVE_SUCCESS';
export const TRANSFERTOUR_UPDATE_UPDATE_VIOLATIONS = 'TRANSFERTOUR_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const TRANSFERTOUR_DELETE_ERROR = 'TRANSFERTOUR_DELETE_ERROR';
export const TRANSFERTOUR_DELETE_LOADING = 'TRANSFERTOUR_DELETE_LOADING';
export const TRANSFERTOUR_DELETE_SUCCESS = 'TRANSFERTOUR_DELETE_SUCCESS';
export const TRANSFERTOUR_DELETE_RESET = 'TRANSFERTOUR_DELETE_RESET';

// List types
export const TRANSFERTOUR_LIST_ERROR = 'TRANSFERTOUR_LIST_ERROR';
export const TRANSFERTOUR_LIST_LOADING = 'TRANSFERTOUR_LIST_LOADING';
export const TRANSFERTOUR_LIST_RESET = 'TRANSFERTOUR_LIST_RESET';
export const TRANSFERTOUR_LIST_VIEW = 'TRANSFERTOUR_LIST_VIEW';
export const TRANSFERTOUR_LIST_SUCCESS = 'TRANSFERTOUR_LIST_SUCCESS';
