// Create types
export const TRANSFERCOMPANY_CREATE_ERROR = 'TRANSFERCOMPANY_CREATE_ERROR';
export const TRANSFERCOMPANY_CREATE_LOADING = 'TRANSFERCOMPANY_CREATE_LOADING';
export const TRANSFERCOMPANY_CREATE_SUCCESS = 'TRANSFERCOMPANY_CREATE_SUCCESS';
export const TRANSFERCOMPANY_CREATE_VIOLATIONS = 'TRANSFERCOMPANY_CREATE_VIOLATIONS';
export const TRANSFERCOMPANY_CREATE_RESET = 'TRANSFERCOMPANY_CREATE_RESET';

// Update types
export const TRANSFERCOMPANY_UPDATE_RESET = 'TRANSFERCOMPANY_UPDATE_RESET';
export const TRANSFERCOMPANY_UPDATE_UPDATE_ERROR = 'TRANSFERCOMPANY_UPDATE_UPDATE_ERROR';
export const TRANSFERCOMPANY_UPDATE_UPDATE_LOADING = 'TRANSFERCOMPANY_UPDATE_UPDATE_LOADING';
export const TRANSFERCOMPANY_UPDATE_UPDATE_SUCCESS = 'TRANSFERCOMPANY_UPDATE_UPDATE_SUCCESS';
export const TRANSFERCOMPANY_UPDATE_RETRIEVE_ERROR = 'TRANSFERCOMPANY_UPDATE_RETRIEVE_ERROR';
export const TRANSFERCOMPANY_UPDATE_RETRIEVE_LOADING = 'TRANSFERCOMPANY_UPDATE_RETRIEVE_LOADING';
export const TRANSFERCOMPANY_UPDATE_RETRIEVE_SUCCESS = 'TRANSFERCOMPANY_UPDATE_RETRIEVE_SUCCESS';
export const TRANSFERCOMPANY_UPDATE_UPDATE_VIOLATIONS = 'TRANSFERCOMPANY_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const TRANSFERCOMPANY_DELETE_ERROR = 'TRANSFERCOMPANY_DELETE_ERROR';
export const TRANSFERCOMPANY_DELETE_LOADING = 'TRANSFERCOMPANY_DELETE_LOADING';
export const TRANSFERCOMPANY_DELETE_SUCCESS = 'TRANSFERCOMPANY_DELETE_SUCCESS';
export const TRANSFERCOMPANY_DELETE_RESET = 'TRANSFERCOMPANY_DELETE_RESET';

// List types
export const TRANSFERCOMPANY_LIST_ERROR = 'TRANSFERCOMPANY_LIST_ERROR';
export const TRANSFERCOMPANY_LIST_LOADING = 'TRANSFERCOMPANY_LIST_LOADING';
export const TRANSFERCOMPANY_LIST_RESET = 'TRANSFERCOMPANY_LIST_RESET';
export const TRANSFERCOMPANY_LIST_VIEW = 'TRANSFERCOMPANY_LIST_VIEW';
export const TRANSFERCOMPANY_LIST_SUCCESS = 'TRANSFERCOMPANY_LIST_SUCCESS';
