// Create types
export const TRANSFER_CREATE_ERROR = 'TRANSFER_CREATE_ERROR';
export const TRANSFER_CREATE_LOADING = 'TRANSFER_CREATE_LOADING';
export const TRANSFER_CREATE_SUCCESS = 'TRANSFER_CREATE_SUCCESS';
export const TRANSFER_CREATE_VIOLATIONS = 'TRANSFER_CREATE_VIOLATIONS';
export const TRANSFER_CREATE_RESET = 'TRANSFER_CREATE_RESET';

// Show types
export const TRANSFER_SHOW_ERROR = 'TRANSFER_SHOW_ERROR';
export const TRANSFER_SHOW_LOADING = 'TRANSFER_SHOW_LOADING';
export const TRANSFER_SHOW_RETRIEVED_SUCCESS = 'TRANSFER_SHOW_RETRIEVED_SUCCESS';
export const TRANSFER_SHOW_RESET = 'TRANSFER_SHOW_RESET';

// Update types
export const TRANSFER_UPDATE_RESET = 'TRANSFER_UPDATE_RESET';
export const TRANSFER_UPDATE_UPDATE_ERROR = 'TRANSFER_UPDATE_UPDATE_ERROR';
export const TRANSFER_UPDATE_UPDATE_LOADING = 'TRANSFER_UPDATE_UPDATE_LOADING';
export const TRANSFER_UPDATE_UPDATE_SUCCESS = 'TRANSFER_UPDATE_UPDATE_SUCCESS';
export const TRANSFER_UPDATE_RETRIEVE_ERROR = 'TRANSFER_UPDATE_RETRIEVE_ERROR';
export const TRANSFER_UPDATE_RETRIEVE_LOADING = 'TRANSFER_UPDATE_RETRIEVE_LOADING';
export const TRANSFER_UPDATE_RETRIEVE_SUCCESS = 'TRANSFER_UPDATE_RETRIEVE_SUCCESS';
export const TRANSFER_UPDATE_UPDATE_VIOLATIONS = 'TRANSFER_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const TRANSFER_DELETE_ERROR = 'TRANSFER_DELETE_ERROR';
export const TRANSFER_DELETE_LOADING = 'TRANSFER_DELETE_LOADING';
export const TRANSFER_DELETE_SUCCESS = 'TRANSFER_DELETE_SUCCESS';
export const TRANSFER_DELETE_RESET = 'TRANSFER_DELETE_RESET';

// List types
export const TRANSFER_LIST_ERROR = 'TRANSFER_LIST_ERROR';
export const TRANSFER_LIST_LOADING = 'TRANSFER_LIST_LOADING';
export const TRANSFER_LIST_RESET = 'TRANSFER_LIST_RESET';
export const TRANSFER_LIST_VIEW = 'TRANSFER_LIST_VIEW';
export const TRANSFER_LIST_SUCCESS = 'TRANSFER_LIST_SUCCESS';
