// Create types
export const LSTOURTEMPLATE_CREATE_ERROR = 'LSTOURTEMPLATE_CREATE_ERROR';
export const LSTOURTEMPLATE_CREATE_LOADING = 'LSTOURTEMPLATE_CREATE_LOADING';
export const LSTOURTEMPLATE_CREATE_SUCCESS = 'LSTOURTEMPLATE_CREATE_SUCCESS';
export const LSTOURTEMPLATE_CREATE_VIOLATIONS = 'LSTOURTEMPLATE_CREATE_VIOLATIONS';
export const LSTOURTEMPLATE_CREATE_RESET = 'LSTOURTEMPLATE_CREATE_RESET';

// Show types
export const LSTOURTEMPLATE_SHOW_ERROR = 'LSTOURTEMPLATE_SHOW_ERROR';
export const LSTOURTEMPLATE_SHOW_LOADING = 'LSTOURTEMPLATE_SHOW_LOADING';
export const LSTOURTEMPLATE_SHOW_RETRIEVED_SUCCESS = 'LSTOURTEMPLATE_SHOW_RETRIEVED_SUCCESS';
export const LSTOURTEMPLATE_SHOW_RESET = 'LSTOURTEMPLATE_SHOW_RESET';

// Update types
export const LSTOURTEMPLATE_UPDATE_RESET = 'LSTOURTEMPLATE_UPDATE_RESET';
export const LSTOURTEMPLATE_UPDATE_UPDATE_ERROR = 'LSTOURTEMPLATE_UPDATE_UPDATE_ERROR';
export const LSTOURTEMPLATE_UPDATE_UPDATE_LOADING = 'LSTOURTEMPLATE_UPDATE_UPDATE_LOADING';
export const LSTOURTEMPLATE_UPDATE_UPDATE_SUCCESS = 'LSTOURTEMPLATE_UPDATE_UPDATE_SUCCESS';
export const LSTOURTEMPLATE_UPDATE_RETRIEVE_ERROR = 'LSTOURTEMPLATE_UPDATE_RETRIEVE_ERROR';
export const LSTOURTEMPLATE_UPDATE_RETRIEVE_LOADING = 'LSTOURTEMPLATE_UPDATE_RETRIEVE_LOADING';
export const LSTOURTEMPLATE_UPDATE_RETRIEVE_SUCCESS = 'LSTOURTEMPLATE_UPDATE_RETRIEVE_SUCCESS';
export const LSTOURTEMPLATE_UPDATE_UPDATE_VIOLATIONS = 'LSTOURTEMPLATE_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const LSTOURTEMPLATE_DELETE_ERROR = 'LSTOURTEMPLATE_DELETE_ERROR';
export const LSTOURTEMPLATE_DELETE_LOADING = 'LSTOURTEMPLATE_DELETE_LOADING';
export const LSTOURTEMPLATE_DELETE_SUCCESS = 'LSTOURTEMPLATE_DELETE_SUCCESS';
export const LSTOURTEMPLATE_DELETE_RESET = 'LSTOURTEMPLATE_DELETE_RESET';

// List types
export const LSTOURTEMPLATE_LIST_ERROR = 'LSTOURTEMPLATE_LIST_ERROR';
export const LSTOURTEMPLATE_LIST_LOADING = 'LSTOURTEMPLATE_LIST_LOADING';
export const LSTOURTEMPLATE_LIST_RESET = 'LSTOURTEMPLATE_LIST_RESET';
export const LSTOURTEMPLATE_LIST_VIEW = 'LSTOURTEMPLATE_LIST_VIEW';
export const LSTOURTEMPLATE_LIST_SUCCESS = 'LSTOURTEMPLATE_LIST_SUCCESS';

//Notification types
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS';
