// Create types
export const HTCTOUR_CREATE_ERROR = 'HTCTOUR_CREATE_ERROR';
export const HTCTOUR_CREATE_LOADING = 'HTCTOUR_CREATE_LOADING';
export const HTCTOUR_CREATE_SUCCESS = 'HTCTOUR_CREATE_SUCCESS';
export const HTCTOUR_CREATE_VIOLATIONS = 'HTCTOUR_CREATE_VIOLATIONS';
export const HTCTOUR_CREATE_RESET = 'HTCTOUR_CREATE_RESET';

// Show types
export const HTCTOUR_SHOW_ERROR = 'HTCTOUR_SHOW_ERROR';
export const HTCTOUR_SHOW_LOADING = 'HTCTOUR_SHOW_LOADING';
export const HTCTOUR_SHOW_RETRIEVED_SUCCESS = 'HTCTOUR_SHOW_RETRIEVED_SUCCESS';
export const HTCTOUR_SHOW_RESET = 'HTCTOUR_SHOW_RESET';

// Update types
export const HTCTOUR_UPDATE_RESET = 'HTCTOUR_UPDATE_RESET';
export const HTCTOUR_UPDATE_UPDATE_ERROR = 'HTCTOUR_UPDATE_UPDATE_ERROR';
export const HTCTOUR_UPDATE_UPDATE_LOADING = 'HTCTOUR_UPDATE_UPDATE_LOADING';
export const HTCTOUR_UPDATE_UPDATE_SUCCESS = 'HTCTOUR_UPDATE_UPDATE_SUCCESS';
export const HTCTOUR_UPDATE_RETRIEVE_ERROR = 'HTCTOUR_UPDATE_RETRIEVE_ERROR';
export const HTCTOUR_UPDATE_RETRIEVE_LOADING = 'HTCTOUR_UPDATE_RETRIEVE_LOADING';
export const HTCTOUR_UPDATE_RETRIEVE_SUCCESS = 'HTCTOUR_UPDATE_RETRIEVE_SUCCESS';
export const HTCTOUR_UPDATE_UPDATE_VIOLATIONS = 'HTCTOUR_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const HTCTOUR_DELETE_ERROR = 'HTCTOUR_DELETE_ERROR';
export const HTCTOUR_DELETE_LOADING = 'HTCTOUR_DELETE_LOADING';
export const HTCTOUR_DELETE_SUCCESS = 'HTCTOUR_DELETE_SUCCESS';
export const HTCTOUR_DELETE_RESET = 'HTCTOUR_DELETE_RESET';

// List types
export const HTCTOUR_LIST_ERROR = 'HTCTOUR_LIST_ERROR';
export const HTCTOUR_LIST_LOADING = 'HTCTOUR_LIST_LOADING';
export const HTCTOUR_LIST_RESET = 'HTCTOUR_LIST_RESET';
export const HTCTOUR_LIST_VIEW = 'HTCTOUR_LIST_VIEW';
export const HTCTOUR_LIST_SUCCESS = 'HTCTOUR_LIST_SUCCESS';
export const HTCTOUR_LIST_SUCCESS_ITEMS_LIST = 'HTCTOUR_LIST_SUCCESS_ITEMS_LIST';
