// Create types
export const LSTOUR_CREATE_ERROR = 'LSTOUR_CREATE_ERROR';
export const LSTOUR_CREATE_LOADING = 'LSTOUR_CREATE_LOADING';
export const LSTOUR_CREATE_SUCCESS = 'LSTOUR_CREATE_SUCCESS';
export const LSTOUR_CREATE_VIOLATIONS = 'LSTOUR_CREATE_VIOLATIONS';
export const LSTOUR_CREATE_RESET = 'LSTOUR_CREATE_RESET';

// Show types
export const LSTOUR_SHOW_ERROR = 'LSTOUR_SHOW_ERROR';
export const LSTOUR_SHOW_LOADING = 'LSTOUR_SHOW_LOADING';
export const LSTOUR_SHOW_RETRIEVED_SUCCESS = 'LSTOUR_SHOW_RETRIEVED_SUCCESS';
export const LSTOUR_SHOW_RESET = 'LSTOUR_SHOW_RESET';

// Update types
export const LSTOUR_UPDATE_RESET = 'LSTOUR_UPDATE_RESET';
export const LSTOUR_UPDATE_UPDATE_ERROR = 'LSTOUR_UPDATE_UPDATE_ERROR';
export const LSTOUR_UPDATE_UPDATE_LOADING = 'LSTOUR_UPDATE_UPDATE_LOADING';
export const LSTOUR_UPDATE_UPDATE_SUCCESS = 'LSTOUR_UPDATE_UPDATE_SUCCESS';
export const LSTOUR_UPDATE_RETRIEVE_ERROR = 'LSTOUR_UPDATE_RETRIEVE_ERROR';
export const LSTOUR_UPDATE_RETRIEVE_LOADING = 'LSTOUR_UPDATE_RETRIEVE_LOADING';
export const LSTOUR_UPDATE_RETRIEVE_SUCCESS = 'LSTOUR_UPDATE_RETRIEVE_SUCCESS';
export const LSTOUR_UPDATE_UPDATE_VIOLATIONS = 'LSTOUR_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const LSTOUR_DELETE_ERROR = 'LSTOUR_DELETE_ERROR';
export const LSTOUR_DELETE_LOADING = 'LSTOUR_DELETE_LOADING';
export const LSTOUR_DELETE_SUCCESS = 'LSTOUR_DELETE_SUCCESS';
export const LSTOUR_DELETE_RESET = 'LSTOUR_DELETE_RESET';

// List types
export const LSTOUR_LIST_ERROR = 'LSTOUR_LIST_ERROR';
export const LSTOUR_LIST_LOADING = 'LSTOUR_LIST_LOADING';
export const LSTOUR_LIST_RESET = 'LSTOUR_LIST_RESET';
export const LSTOUR_LIST_VIEW = 'LSTOUR_LIST_VIEW';
export const LSTOUR_LIST_SUCCESS = 'LSTOUR_LIST_SUCCESS';
export const LSTOUR_LIST_SUCCESS_ITEMS_LIST = 'LSTOUR_LIST_SUCCESS_ITEMS_LIST';
export const TOURS_FOR_SHEDULE = 'TOURS_FOR_SHEDULE';
