// Create types
export const GUIDE_CREATE_ERROR = 'GUIDE_CREATE_ERROR';
export const GUIDE_CREATE_LOADING = 'GUIDE_CREATE_LOADING';
export const GUIDE_CREATE_SUCCESS = 'GUIDE_CREATE_SUCCESS';
export const GUIDE_CREATE_VIOLATIONS = 'GUIDE_CREATE_VIOLATIONS';
export const GUIDE_CREATE_RESET = 'GUIDE_CREATE_RESET';

// Update types
export const GUIDE_UPDATE_RESET = 'GUIDE_UPDATE_RESET';
export const GUIDE_UPDATE_UPDATE_ERROR = 'GUIDE_UPDATE_UPDATE_ERROR';
export const GUIDE_UPDATE_UPDATE_LOADING = 'GUIDE_UPDATE_UPDATE_LOADING';
export const GUIDE_UPDATE_UPDATE_SUCCESS = 'GUIDE_UPDATE_UPDATE_SUCCESS';
export const GUIDE_UPDATE_RETRIEVE_ERROR = 'GUIDE_UPDATE_RETRIEVE_ERROR';
export const GUIDE_UPDATE_RETRIEVE_LOADING = 'GUIDE_UPDATE_RETRIEVE_LOADING';
export const GUIDE_UPDATE_RETRIEVE_SUCCESS = 'GUIDE_UPDATE_RETRIEVE_SUCCESS';
export const GUIDE_UPDATE_UPDATE_VIOLATIONS = 'GUIDE_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const GUIDE_DELETE_ERROR = 'GUIDE_DELETE_ERROR';
export const GUIDE_DELETE_LOADING = 'GUIDE_DELETE_LOADING';
export const GUIDE_DELETE_SUCCESS = 'GUIDE_DELETE_SUCCESS';
export const GUIDE_DELETE_RESET = 'GUIDE_DELETE_RESET';

// List types
export const GUIDE_LIST_ERROR = 'GUIDE_LIST_ERROR';
export const GUIDE_LIST_LOADING = 'GUIDE_LIST_LOADING';
export const GUIDE_LIST_RESET = 'GUIDE_LIST_RESET';
export const GUIDE_LIST_VIEW = 'GUIDE_LIST_VIEW';
export const GUIDE_LIST_SUCCESS = 'GUIDE_LIST_SUCCESS';
