// Create types
export const TOUROFFICE_CREATE_ERROR = 'TOUROFFICE_CREATE_ERROR';
export const TOUROFFICE_CREATE_LOADING = 'TOUROFFICE_CREATE_LOADING';
export const TOUROFFICE_CREATE_SUCCESS = 'TOUROFFICE_CREATE_SUCCESS';
export const TOUROFFICE_CREATE_VIOLATIONS = 'TOUROFFICE_CREATE_VIOLATIONS';
export const TOUROFFICE_CREATE_RESET = 'TOUROFFICE_CREATE_RESET';

// Show types
export const TOUROFFICE_SHOW_ERROR = 'TOUROFFICE_SHOW_ERROR';
export const TOUROFFICE_SHOW_LOADING = 'TOUROFFICE_SHOW_LOADING';
export const TOUROFFICE_SHOW_RETRIEVED_SUCCESS = 'TOUROFFICE_SHOW_RETRIEVED_SUCCESS';
export const TOUROFFICE_SHOW_RESET = 'TOUROFFICE_SHOW_RESET';

// Update types
export const TOUROFFICE_UPDATE_RESET = 'TOUROFFICE_UPDATE_RESET';
export const TOUROFFICE_UPDATE_UPDATE_ERROR = 'TOUROFFICE_UPDATE_UPDATE_ERROR';
export const TOUROFFICE_UPDATE_UPDATE_LOADING = 'TOUROFFICE_UPDATE_UPDATE_LOADING';
export const TOUROFFICE_UPDATE_UPDATE_SUCCESS = 'TOUROFFICE_UPDATE_UPDATE_SUCCESS';
export const TOUROFFICE_UPDATE_RETRIEVE_ERROR = 'TOUROFFICE_UPDATE_RETRIEVE_ERROR';
export const TOUROFFICE_UPDATE_RETRIEVE_LOADING = 'TOUROFFICE_UPDATE_RETRIEVE_LOADING';
export const TOUROFFICE_UPDATE_RETRIEVE_SUCCESS = 'TOUROFFICE_UPDATE_RETRIEVE_SUCCESS';
export const TOUROFFICE_UPDATE_UPDATE_VIOLATIONS = 'TOUROFFICE_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const TOUROFFICE_DELETE_ERROR = 'TOUROFFICE_DELETE_ERROR';
export const TOUROFFICE_DELETE_LOADING = 'TOUROFFICE_DELETE_LOADING';
export const TOUROFFICE_DELETE_SUCCESS = 'TOUROFFICE_DELETE_SUCCESS';
export const TOUROFFICE_DELETE_RESET = 'TOUROFFICE_DELETE_RESET';

// List types
export const TOUROFFICE_LIST_ERROR = 'TOUROFFICE_LIST_ERROR';
export const TOUROFFICE_LIST_LOADING = 'TOUROFFICE_LIST_LOADING';
export const TOUROFFICE_LIST_RESET = 'TOUROFFICE_LIST_RESET';
export const TOUROFFICE_LIST_VIEW = 'TOUROFFICE_LIST_VIEW';
export const TOUROFFICE_LIST_SUCCESS = 'TOUROFFICE_LIST_SUCCESS';
