// Create types
export const BOOKING_CREATE_ERROR = 'BOOKING_CREATE_ERROR';
export const BOOKING_CREATE_LOADING = 'BOOKING_CREATE_LOADING';
export const BOOKING_CREATE_SUCCESS = 'BOOKING_CREATE_SUCCESS';
export const BOOKING_CREATE_VIOLATIONS = 'BOOKING_CREATE_VIOLATIONS';
export const BOOKING_CREATE_RESET = 'BOOKING_CREATE_RESET';

// Show types
export const BOOKING_SHOW_ERROR = 'BOOKING_SHOW_ERROR';
export const BOOKING_SHOW_LOADING = 'BOOKING_SHOW_LOADING';
export const BOOKING_SHOW_RETRIEVED_SUCCESS = 'BOOKING_SHOW_RETRIEVED_SUCCESS';
export const BOOKING_SHOW_RESET = 'BOOKING_SHOW_RESET';

// Update types
export const BOOKING_UPDATE_RESET = 'BOOKING_UPDATE_RESET';
export const BOOKING_UPDATE_UPDATE_ERROR = 'BOOKING_UPDATE_UPDATE_ERROR';
export const BOOKING_UPDATE_UPDATE_LOADING = 'BOOKING_UPDATE_UPDATE_LOADING';
export const BOOKING_UPDATE_UPDATE_SUCCESS = 'BOOKING_UPDATE_UPDATE_SUCCESS';
export const BOOKING_UPDATE_RETRIEVE_ERROR = 'BOOKING_UPDATE_RETRIEVE_ERROR';
export const BOOKING_UPDATE_RETRIEVE_LOADING = 'BOOKING_UPDATE_RETRIEVE_LOADING';
export const BOOKING_UPDATE_RETRIEVE_SUCCESS = 'BOOKING_UPDATE_RETRIEVE_SUCCESS';
export const BOOKING_UPDATE_UPDATE_VIOLATIONS = 'BOOKING_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const BOOKING_DELETE_ERROR = 'BOOKING_DELETE_ERROR';
export const BOOKING_DELETE_LOADING = 'BOOKING_DELETE_LOADING';
export const BOOKING_DELETE_SUCCESS = 'BOOKING_DELETE_SUCCESS';
export const BOOKING_DELETE_RESET = 'BOOKING_DELETE_RESET';

// List types
export const BOOKING_LIST_ERROR = 'BOOKING_LIST_ERROR';
export const BOOKING_LIST_LOADING = 'BOOKING_LIST_LOADING';
export const BOOKING_LIST_RESET = 'BOOKING_LIST_RESET';
export const BOOKING_LIST_VIEW = 'BOOKING_LIST_VIEW';
export const BOOKING_LIST_SUCCESS = 'BOOKING_LIST_SUCCESS';
