// Create types
export const ICON_CREATE_ERROR = 'ICON_CREATE_ERROR';
export const ICON_CREATE_LOADING = 'ICON_CREATE_LOADING';
export const ICON_CREATE_SUCCESS = 'ICON_CREATE_SUCCESS';
export const ICON_CREATE_VIOLATIONS = 'ICON_CREATE_VIOLATIONS';
export const ICON_CREATE_RESET = 'ICON_CREATE_RESET';

// Update types
export const ICON_UPDATE_RESET = 'ICON_UPDATE_RESET';
export const ICON_UPDATE_UPDATE_ERROR = 'ICON_UPDATE_UPDATE_ERROR';
export const ICON_UPDATE_UPDATE_LOADING = 'ICON_UPDATE_UPDATE_LOADING';
export const ICON_UPDATE_UPDATE_SUCCESS = 'ICON_UPDATE_UPDATE_SUCCESS';
export const ICON_UPDATE_RETRIEVE_ERROR = 'ICON_UPDATE_RETRIEVE_ERROR';
export const ICON_UPDATE_RETRIEVE_LOADING = 'ICON_UPDATE_RETRIEVE_LOADING';
export const ICON_UPDATE_RETRIEVE_SUCCESS = 'ICON_UPDATE_RETRIEVE_SUCCESS';
export const ICON_UPDATE_UPDATE_VIOLATIONS = 'ICON_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const ICON_DELETE_ERROR = 'ICON_DELETE_ERROR';
export const ICON_DELETE_LOADING = 'ICON_DELETE_LOADING';
export const ICON_DELETE_SUCCESS = 'ICON_DELETE_SUCCESS';
export const ICON_DELETE_RESET = 'ICON_DELETE_RESET';

// List types
export const ICON_LIST_ERROR = 'ICON_LIST_ERROR';
export const ICON_LIST_LOADING = 'ICON_LIST_LOADING';
export const ICON_LIST_RESET = 'ICON_LIST_RESET';
export const ICON_LIST_VIEW = 'ICON_LIST_VIEW';
export const ICON_LIST_SUCCESS = 'ICON_LIST_SUCCESS';
