// Create types
export const TRANSFERRECEPTIVE_CREATE_ERROR = 'TRANSFERRECEPTIVE_CREATE_ERROR';
export const TRANSFERRECEPTIVE_CREATE_LOADING = 'TRANSFERRECEPTIVE_CREATE_LOADING';
export const TRANSFERRECEPTIVE_CREATE_SUCCESS = 'TRANSFERRECEPTIVE_CREATE_SUCCESS';
export const TRANSFERRECEPTIVE_CREATE_VIOLATIONS = 'TRANSFERRECEPTIVE_CREATE_VIOLATIONS';
export const TRANSFERRECEPTIVE_CREATE_RESET = 'TRANSFERRECEPTIVE_CREATE_RESET';

// Update types
export const TRANSFERRECEPTIVE_UPDATE_RESET = 'TRANSFERRECEPTIVE_UPDATE_RESET';
export const TRANSFERRECEPTIVE_UPDATE_UPDATE_ERROR = 'TRANSFERRECEPTIVE_UPDATE_UPDATE_ERROR';
export const TRANSFERRECEPTIVE_UPDATE_UPDATE_LOADING = 'TRANSFERRECEPTIVE_UPDATE_UPDATE_LOADING';
export const TRANSFERRECEPTIVE_UPDATE_UPDATE_SUCCESS = 'TRANSFERRECEPTIVE_UPDATE_UPDATE_SUCCESS';
export const TRANSFERRECEPTIVE_UPDATE_RETRIEVE_ERROR = 'TRANSFERRECEPTIVE_UPDATE_RETRIEVE_ERROR';
export const TRANSFERRECEPTIVE_UPDATE_RETRIEVE_LOADING = 'TRANSFERRECEPTIVE_UPDATE_RETRIEVE_LOADING';
export const TRANSFERRECEPTIVE_UPDATE_RETRIEVE_SUCCESS = 'TRANSFERRECEPTIVE_UPDATE_RETRIEVE_SUCCESS';
export const TRANSFERRECEPTIVE_UPDATE_UPDATE_VIOLATIONS = 'TRANSFERRECEPTIVE_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const TRANSFERRECEPTIVE_DELETE_ERROR = 'TRANSFERRECEPTIVE_DELETE_ERROR';
export const TRANSFERRECEPTIVE_DELETE_LOADING = 'TRANSFERRECEPTIVE_DELETE_LOADING';
export const TRANSFERRECEPTIVE_DELETE_SUCCESS = 'TRANSFERRECEPTIVE_DELETE_SUCCESS';
export const TRANSFERRECEPTIVE_DELETE_RESET = 'TRANSFERRECEPTIVE_DELETE_RESET';

// List types
export const TRANSFERRECEPTIVE_LIST_ERROR = 'TRANSFERRECEPTIVE_LIST_ERROR';
export const TRANSFERRECEPTIVE_LIST_LOADING = 'TRANSFERRECEPTIVE_LIST_LOADING';
export const TRANSFERRECEPTIVE_LIST_RESET = 'TRANSFERRECEPTIVE_LIST_RESET';
export const TRANSFERRECEPTIVE_LIST_VIEW = 'TRANSFERRECEPTIVE_LIST_VIEW';
export const TRANSFERRECEPTIVE_LIST_SUCCESS = 'TRANSFERRECEPTIVE_LIST_SUCCESS';
