// Create types
export const DRIVER_CREATE_ERROR = 'DRIVER_CREATE_ERROR';
export const DRIVER_CREATE_LOADING = 'DRIVER_CREATE_LOADING';
export const DRIVER_CREATE_SUCCESS = 'DRIVER_CREATE_SUCCESS';
export const DRIVER_CREATE_VIOLATIONS = 'DRIVER_CREATE_VIOLATIONS';
export const DRIVER_CREATE_RESET = 'DRIVER_CREATE_RESET';

// Show types
export const DRIVER_SHOW_ERROR = 'DRIVER_SHOW_ERROR';
export const DRIVER_SHOW_LOADING = 'DRIVER_SHOW_LOADING';
export const DRIVER_SHOW_RETRIEVED_SUCCESS = 'DRIVER_SHOW_RETRIEVED_SUCCESS';
export const DRIVER_SHOW_RESET = 'DRIVER_SHOW_RESET';

// Update types
export const DRIVER_UPDATE_RESET = 'DRIVER_UPDATE_RESET';
export const DRIVER_UPDATE_UPDATE_ERROR = 'DRIVER_UPDATE_UPDATE_ERROR';
export const DRIVER_UPDATE_UPDATE_LOADING = 'DRIVER_UPDATE_UPDATE_LOADING';
export const DRIVER_UPDATE_UPDATE_SUCCESS = 'DRIVER_UPDATE_UPDATE_SUCCESS';
export const DRIVER_UPDATE_RETRIEVE_ERROR = 'DRIVER_UPDATE_RETRIEVE_ERROR';
export const DRIVER_UPDATE_RETRIEVE_LOADING = 'DRIVER_UPDATE_RETRIEVE_LOADING';
export const DRIVER_UPDATE_RETRIEVE_SUCCESS = 'DRIVER_UPDATE_RETRIEVE_SUCCESS';
export const DRIVER_UPDATE_UPDATE_VIOLATIONS = 'DRIVER_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const DRIVER_DELETE_ERROR = 'DRIVER_DELETE_ERROR';
export const DRIVER_DELETE_LOADING = 'DRIVER_DELETE_LOADING';
export const DRIVER_DELETE_SUCCESS = 'DRIVER_DELETE_SUCCESS';
export const DRIVER_DELETE_RESET = 'DRIVER_DELETE_RESET';

// List types
export const DRIVER_LIST_ERROR = 'DRIVER_LIST_ERROR';
export const DRIVER_LIST_LOADING = 'DRIVER_LIST_LOADING';
export const DRIVER_LIST_RESET = 'DRIVER_LIST_RESET';
export const DRIVER_LIST_VIEW = 'DRIVER_LIST_VIEW';
export const DRIVER_LIST_SUCCESS = 'DRIVER_LIST_SUCCESS';
