// Create types
export const HTCTOURTEMPLATE_CREATE_ERROR = 'HTCTOURTEMPLATE_CREATE_ERROR';
export const HTCTOURTEMPLATE_CREATE_LOADING = 'HTCTOURTEMPLATE_CREATE_LOADING';
export const HTCTOURTEMPLATE_CREATE_SUCCESS = 'HTCTOURTEMPLATE_CREATE_SUCCESS';
export const HTCTOURTEMPLATE_CREATE_VIOLATIONS = 'HTCTOURTEMPLATE_CREATE_VIOLATIONS';
export const HTCTOURTEMPLATE_CREATE_RESET = 'HTCTOURTEMPLATE_CREATE_RESET';

// Show types
export const HTCTOURTEMPLATE_SHOW_ERROR = 'HTCTOURTEMPLATE_SHOW_ERROR';
export const HTCTOURTEMPLATE_SHOW_LOADING = 'HTCTOURTEMPLATE_SHOW_LOADING';
export const HTCTOURTEMPLATE_SHOW_RETRIEVED_SUCCESS = 'HTCTOURTEMPLATE_SHOW_RETRIEVED_SUCCESS';
export const HTCTOURTEMPLATE_SHOW_RESET = 'HTCTOURTEMPLATE_SHOW_RESET';

// Update types
export const HTCTOURTEMPLATE_UPDATE_RESET = 'HTCTOURTEMPLATE_UPDATE_RESET';
export const HTCTOURTEMPLATE_UPDATE_UPDATE_ERROR = 'HTCTOURTEMPLATE_UPDATE_UPDATE_ERROR';
export const HTCTOURTEMPLATE_UPDATE_UPDATE_LOADING = 'HTCTOURTEMPLATE_UPDATE_UPDATE_LOADING';
export const HTCTOURTEMPLATE_UPDATE_UPDATE_SUCCESS = 'HTCTOURTEMPLATE_UPDATE_UPDATE_SUCCESS';
export const HTCTOURTEMPLATE_UPDATE_RETRIEVE_ERROR = 'HTCTOURTEMPLATE_UPDATE_RETRIEVE_ERROR';
export const HTCTOURTEMPLATE_UPDATE_RETRIEVE_LOADING = 'HTCTOURTEMPLATE_UPDATE_RETRIEVE_LOADING';
export const HTCTOURTEMPLATE_UPDATE_RETRIEVE_SUCCESS = 'HTCTOURTEMPLATE_UPDATE_RETRIEVE_SUCCESS';
export const HTCTOURTEMPLATE_UPDATE_UPDATE_VIOLATIONS = 'HTCTOURTEMPLATE_UPDATE_UPDATE_VIOLATIONS';

// Delete types
export const HTCTOURTEMPLATE_DELETE_ERROR = 'HTCTOURTEMPLATE_DELETE_ERROR';
export const HTCTOURTEMPLATE_DELETE_LOADING = 'HTCTOURTEMPLATE_DELETE_LOADING';
export const HTCTOURTEMPLATE_DELETE_SUCCESS = 'HTCTOURTEMPLATE_DELETE_SUCCESS';
export const HTCTOURTEMPLATE_DELETE_RESET = 'HTCTOURTEMPLATE_DELETE_RESET';

// List types
export const HTCTOURTEMPLATE_LIST_ERROR = 'HTCTOURTEMPLATE_LIST_ERROR';
export const HTCTOURTEMPLATE_LIST_LOADING = 'HTCTOURTEMPLATE_LIST_LOADING';
export const HTCTOURTEMPLATE_LIST_RESET = 'HTCTOURTEMPLATE_LIST_RESET';
export const HTCTOURTEMPLATE_LIST_VIEW = 'HTCTOURTEMPLATE_LIST_VIEW';
export const HTCTOURTEMPLATE_LIST_SUCCESS = 'HTCTOURTEMPLATE_LIST_SUCCESS';

//Notification types
export const NOTIFICATION_LIST_SUCCESS = 'NOTIFICATION_LIST_SUCCESS';
